sudo: required

services:
  - docker

script:
  - docker build -t taiga-back .
  - docker run --name postgres -d kiasaki/alpine-postgres
  - docker run --name taiback --link postgres -p 8000:8000 -e SAMPLE_DATA=true -d taiga-back

  - echo "Waiting for Taiga Backend to get up and running"
  - while ! echo exit | nc localhost 8000; do sleep 15; done

  - docker exec taiback /bin/sh -c "curl -f localhost:8000/api/v1/projects"
  - docker logs taiback
