sudo: required

services:
  - docker

script:
  - docker build -t taiga-back .
  - docker run --name postgres -d kiasaki/alpine-postgres
  - docker run --name taiback --link postgres -p 8000:8000 -e SAMPLE_DATA=true -d taiga-back

  - sleep 420

  - docker exec taiback /bin/sh -c "apk add --no-cache curl && curl -f localhost:8000/api/v1/projects"
  - docker logs taiback
