sudo: required

services:
  - docker

script:
  - docker build -t taiga-back .
  - docker run -d taiga-back
  - docker run --name postgres -e POSTGRES_PASSWORD=Un1c0rn -d postgres
  - docker run --name taiback --link postgres taiga-back
  - docker exec taiback /bin/bash -c "apt-get update && apt-get install curl && curl localhost:8000"
  
